name: b1gmail

on: [push, pull_request, workflow_dispatch]

jobs:
  # The command 'npm ci' already does check whether the dependencies from package-lock.json are up-to-date with the ones from package.json. However, it seems like it ignores certain (small) differences, e.g. if we made small changes to package.json of a linked workspace project that does not influence the dependencies.
  check-package-lock:
    name: Check if package-lock.json is up-to-date
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2

      - name: Calculate the original hash sum
        run: echo "original_package_lock_hash_sum=$(sha256sum package-lock.json)" >> $GITHUB_ENV

      - name: Install npm dependencies
        run: npm install --package-lock-only

      - name: Calculate the new hash sum
        run: echo "new_package_lock_hash_sum=$(sha256sum package-lock.json)" >> $GITHUB_ENV

      - name: Fail if the old and new hash sums are different
        if: env.original_package_lock_hash_sum != env.new_package_lock_hash_sum
        run: |
          echo "It seems like your package-lock.json file is not up-to-date. Try running 'npm install' and commit the changes."
          exit 1

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: Install php dependencies using Composer
        run: composer install

      - name: Run the linter
        run: npm run lint
