name: b1gmail

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2

      - name: Check if package-lock.json is up to date
        run: npx --yes package-lock-utd@1.x.x

      - name: Install npm dependencies
        run: npm ci

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: Install php dependencies using Composer
        run: composer install

      - name: Run the linter
        run: npm run lint
